version: "3.9" # Use a recent version of the Docker Compose file format

services:
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    container_name: mynodered

  mongo:
    image: mongo:4.4
    ports:
      - "27019:27017" # In Docker Network we will use : mongodb://localhost:27017/motor-diagnostics, In Local Server we will use mongodb://localhost:27019/motor-diagnostics
    volumes:
      - mongo_data_project3:/data/db
    container_name: mongo_project3

volumes:
  node_red_data:
  mongo_data_project3: